In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

model = tf.keras.Sequential([keras.layers.Dense(units=4, input_shape=[1], activation=None),# hidden layer
                            keras.layers.Dense(units=1)])
model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model.fit(xs,ys, epochs = 100)



Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - loss: 24.3428
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 14.0759
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 8.6761
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5.3064
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 3.2174
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 2.0212
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1.3971
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.0907
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.9377
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.8515
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.7927
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.7453
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.7033
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.6644
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.6278
Epoch 16/100
1/1 ━━━━━━━━━━━

In [ ]:
ex = np.array([5.0],dtype=float)
model.predict(ex)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[8.9717045]], dtype=float32)

In [ ]:
ex = np.array([10.0],dtype=float)
model.predict(ex)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[18.216152]], dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

model = tf.keras.Sequential([keras.layers.Dense(units=2, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error', metrics=['mae'])

xs = np.array([2,4,6,8,10], dtype=float)
ys = np.array([[8.5,12],
               [10.0,16],
               [11.5,20],
               [13.0,26],
               [14.0,32]], dtype=float)

model.fit(xs,ys, epochs = 500)



Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 529ms/step - loss: 351.9263 - mae: 17.9803
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 112.4153 - mae: 10.4252
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 39.4742 - mae: 6.2555
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 17.2481 - mae: 3.9538
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 10.4630 - mae: 2.7113
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 8.3793 - mae: 2.2377
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 7.7271 - mae: 2.1048
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 7.5108 - mae: 2.1051
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 7.4273 - mae: 2.1295
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 7.3842 - mae: 2.1513
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 7.3536 - mae: 2.1616
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 7.3267 - mae: 2.1657
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0

In [ ]:
ex = np.array([7.0],dtype=float)
model.predict(ex)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[11.983843, 23.600956]], dtype=float32)

In [ ]:
ex = np.array([10.0],dtype=float)
model.predict(ex)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[15.262728, 32.077137]], dtype=float32)